# CommonCrawl text extraction pipeline

data_loader:
  type: CommonCrawlLoader
  params:
    crawl_id: "CC-MAIN-2024-51"
  num_workers: 1

stages:
  - name: content_filtering
    operators:
      - name: url_filter
        params:
          url_field: "url"
      - name: text_length_filter
        params:
          min_length: 50
          max_length: 100000
          text_field: "text"
          length_type: "word"
      - name: text_alphabetic_word_ration_filter
        params:
          text_field: "text"
          max_ratio: 0.2
      - name: text_avg_word_length_filter
        params:
          text_field: "text"
          lower_bound: 3.0
          upper_bound: 10.0
      - name: text_bullet_filter
        params:
          text_field: "text"
          max_bullet_ratio: 0.9
      - name: text_ellipsis_line_ratio_filter
        params:
          text_field: "text"
          max_ratio: 0.3
      - name: text_symbol_ratio_filter
        params:
          text_field: "text"
          max_symbol_to_word_ratio: 0.5
      - name: text_repetition_filter
        params:
          text_field: "text"
      - name: text_new_line_removal_refiner
        params:
          text_field: "text"
          max_consecutive: 2
      - name: text_exact_deduplicator
        params:
          text_field: "text"
      - name: text_target_language_filter
        params:
          text_field: "text"
          target_languages: ["eng"]
          min_score: 0.65
    worker:
      min_replicas: 2
      max_replicas: 2

data_writer:
  type: ParquetDataWriter
  params:
    output_path: "./output/commoncrawl"

executor:
  max_samples: 10000
  batch_size: 200
  dedup_num_buckets: 1
  rejected_samples:
    enabled: true
  metrics:
    enabled: true
    generate_report: true
    debug_samples_per_operator: 20
